server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-proud-meadow-a4wtao6p-pooler.us-east-1.aws.neon.tech:5432/verceldb
    username: default
    password: Dbmidzsvq93P
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false